interface Env {
  APP_ORIGIN: string;
  GOOGLE_CLIENT_ID: string;
  GOOGLE_CLIENT_SECRET: string;
  GOOGLE_REDIRECT_URI: string;
  PASSWORD_PEPPER_CURRENT: string;
  PASSWORD_PEPPER_LEGACY?: string;
  PAYROLL_ENCRYPTION_KEY?: string;
  PAYROLL_PROFILE_REVEAL_LIMIT?: string;
  PAYROLL_PROFILE_REVEAL_WINDOW_SECONDS?: string;
  PAYROLL_PAYSLIP_LIMIT?: string;
  PAYROLL_PAYSLIP_WINDOW_SECONDS?: string;
}
